# Generated by Django 4.1.7 on 2023-03-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_rename_desc1_people_desc_rename_img1_people_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='name1',
        ),
    ]
